### ISSUE TITLE
Prometheus doesn't scrape recursor: 4.6.0-alpha0.1087.master.gb6cfaec15

### ISSUE THREAD

**Issue by KVInventoR** [PowerDNS/pdns#10735]
Looks like this issue come after this changes: 
https://github.com/PowerDNS/pdns/pull/10554

this PR broke scraping metrics by prometheus with error: "expected label value, got "INVALID"

After some digging, 
```
#!/usr/bin/env python3

from prometheus_client.parser import text_string_to_metric_families
import requests
from requests.auth import HTTPBasicAuth


URL="http://endpointip:8082/metrics"

def main():
    metrics = requests.get(URL, auth = HTTPBasicAuth('admin', '0pre')).content
    for family in text_string_to_metric_families(metrics.decode("utf-8")):
        print(family)

if __name__ == "__main__":
    main()%
```
I got:

`Traceback (most recent call last):
  File "/Users/inventor/Develop/scripts/debug_prometheus_metrics/./parse_metrics.py", line 22, in <module>
    main()
  File "/Users/inventor/Develop/scripts/debug_prometheus_metrics/./parse_metrics.py", line 16, in main
    for family in text_string_to_metric_families(metrics.decode("utf-8")):
  File "/Users/inventor/.pyenv/versions/global-3.9.6/lib/python3.9/site-packages/prometheus_client/parser.py", line 20, in text_string_to_metric_families
    for metric_family in text_fd_to_metric_families(StringIO.StringIO(text)):
  File "/Users/inventor/.pyenv/versions/global-3.9.6/lib/python3.9/site-packages/prometheus_client/parser.py", line 227, in text_fd_to_metric_families
    yield build_metric(sample[0], documentation, typ, [sample])
  File "/Users/inventor/.pyenv/versions/global-3.9.6/lib/python3.9/site-packages/prometheus_client/parser.py", line 170, in build_metric
    metric = Metric(name, documentation, typ)
  File "/Users/inventor/.pyenv/versions/global-3.9.6/lib/python3.9/site-packages/prometheus_client/metrics_core.py", line 27, in __init__
    raise ValueError('Invalid metric name: ' + name)
ValueError: Invalid metric name: pdns_recursor_cpu_msec{thread=0}
`

I am pretty sure, that each value of label should  in double quotes
@omoerbeek  could you please take a look. I also tested it with: prometheus v2.30.0

**Comment by omoerbeek** [comment]
Thanks for the report. I'll fix after the weekend and also make sure that we add a regression test for the Prometheus output so that at least it conforms to the proper syntax.

**Comment by rgacogne** [comment]
> I'll fix after the weekend and also make sure that we add a regression test for the Prometheus output so that at least it conforms to the proper syntax.

We use promtool in dnsdist's regression tests for that, it would be nice to check whether it would have caught the issue.

**Comment by omoerbeek** [comment]
> > I'll fix after the weekend and also make sure that we add a regression test for the Prometheus output so that at least it conforms to the proper syntax.
> 
> We use promtool in dnsdist's regression tests for that, it would be nice to check whether it would have caught the issue.

Yep, plan is the first add the test and then fix the issue :-)
