### ISSUE TITLE
rec_control reload-lua-script causes STL errors

### ISSUE THREAD

**Issue by franklouwers** [PowerDNS/pdns#11289]
- Program: Recursor
 - Issue type: Bug report

### Short description
When reloading lua custom code (using rec_control reload-lua-script), it seems (some / all) in-flight queries generate an STL error. I use `dq` objects in Lua, including modifying them.

### Environment
 - Operating system:  Centos 7
 - Software version: 4.4.3.0
 - Software source: PowerDNS repository

### Steps to reproduce
1. Configure pdns-recursor to use Lua hooks, use `dq` and `dq.data` in Lua
2. Have a decent amount of qps :)
2. `rec_control reload-lua-script`

### Expected behaviour
Not crash / Not generate a ServFail or other error, not generate STL errors in the logs

### Actual behaviour
Queries seem to get a ServFail (or other error), and log entries as in https://gist.github.com/franklouwers/28074f09e45dfdd9c2c29a15ea6f7bde appear. (IPs stripped in log)

**Comment by franklouwers** [comment]
Some additional info requested by @Habbie : 

- `preresolve()` handles the bulk of the work, reading and writing to the `dq` object
-  `nodata()` and `nxdomain()` write to `dq`:
```
setting dq.data["nx"] = true)
```
- `postresolve()` reads `dq.data` and `dq.qtype`

The full script is quite extensive and customer specific, I'll try to work on a minimal implementation.

**Comment by omoerbeek** [comment]
I managed to reproduce with a `dnsperf` test and `while true; do ./rc reload-lua-script; sleep 1; done` using the Lua script below.

My recursor is set up to forward-recurse to am IP that does not respond
```
forward-zones-recurse=.=1.2.3.4
dont-throttle-netmasks=1.2.3.4
```
and packet cache is disabled: `disable-packetcache=yes`
```
function preresolve(dq)
  dq.data = {}
  dq.data['status'] = 1
  return false
end

function postresolve(dq)
  dq.data['status'] = 2
  return false
end

function nxdomain(dq)
  dq.data['status'] = 3
  return false
end

function nodata(dq)
  dq.data['status'] = 4
  return false
end
```

backtrace the moment the exception is thrown:
```
(gdb) bt 
#0  __cxa_throw (thrown_object=0x1866fc14180, 
    tinfo=0x18371c1f580 <typeinfo for LuaContext::ExecutionErrorException>, 
    dest=0x185e9589e10 <std::runtime_error::~runtime_error()>)
    at /usr/src/gnu/lib/libcxxabi/../../../gnu/llvm/libcxxabi/src/cxa_exception.cpp:258
#1  0x00000183718b2819 in LuaContext::callRaw (state=0x10260378, functionAndArguments=..., outArguments=1)
    at ./ext/luawrapper/include/LuaContext.hpp:1484
#2  0x00000183719f39d6 in LuaContext::call<bool, RecursorLua4::DNSQuestion*> (state=0x10260378, toCall=..., 
    input=<optimized out>) at ./ext/luawrapper/include/LuaContext.hpp:1413
#3  0x00000183719f384c in LuaContext::LuaFunctionCaller<bool (RecursorLua4::DNSQuestion*)>::operator()(RecursorLua4::DNSQuestion*&&) const (this=0x1866fc2a9d8, params=@0x185e9589e10: 0x49505641e5894855)
    at ./ext/luawrapper/include/LuaContext.hpp:1976
#4  0x0000018371929f7e in std::__1::__function::__value_func<bool (RecursorLua4::DNSQuestion*)>::operator()(RecursorLua4::DNSQuestion*&&) const (this=0x1866fc2a9d0, __args=<optimized out>)
    at /usr/include/c++/v1/__functional/function.h:498
#5  std::__1::function<bool (RecursorLua4::DNSQuestion*)>::operator()(RecursorLua4::DNSQuestion*) const (
    this=0x1866fc2a9d0, __arg=0x185f48595d0) at /usr/include/c++/v1/__functional/function.h:1175
#6  RecursorLua4::genhook(std::__1::function<bool (RecursorLua4::DNSQuestion*)> const&, RecursorLua4::DNSQuestion&, int&) const (this=0x1866fc2a820, func=..., dq=..., ret=<optimized out>) at lua-recursor4.cc:725
#7  0x000001837192aaf1 in RecursorLua4::postresolve (this=0x1866fc2a820, dq=..., ret=@0x185f4859c38: 2, et=...)
    at lua-recursor4.cc:570
#8  0x0000018371a2c19a in startDoResolve (p=<optimized out>) at pdns_recursor.cc:1157
#9  0x0000018371a45228 in MTasker<std::__1::shared_ptr<PacketID>, std::__1::vector<unsigned char, noinit_adaptor<std::__1::allocator<unsigned char> > >, PacketIDCompare>::makeThread(void (*)(void*), void*)::{lambda()#1}::operator()() const (this=0x185f4859d00) at ./mtasker.cc:286
#10 0x0000018371a126f0 in boost::function0<void>::operator() (this=<optimized out>)
    at /usr/local/include/boost/function/function_template.hpp:763
#11 threadWrapper (t=...) at ./mtasker_fcontext.cc:144
#12 0x00000185e1754d9f in make_fcontext () from /usr/local/lib/libboost_context-mt.so.18.0
#13 0x0000000000000000 in ?? ()
```
