### ISSUE TITLE
pdnsutil check-all-zones segfaults

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#3147]
Reported by @stbuehler.

Debian testing/sid,
```
ii  pdns-backend-mysql                        4.0.0~alpha1-1            amd64                     generic MySQL backend for PowerDNS
ii  pdns-server                               4.0.0~alpha1-1            amd64                     extremely powerful and versatile nameserver
```

Can reproduce with gmysql, enable API, create a zone like this, then run `pdnsutil check-all-zones`.

```
curl -XPOST -H 'X-API-Key: changeme' 'http://127.0.0.1:8081/api/v1/servers/localhost/zones' -d '{"name":"example.org.", "kind": "Native", "masters": [], "nameservers": ["ns1.example.org.", "ns2.example.org."]}'
curl -X PATCH --data '{"rrsets": [ {"name": "test.example.org.", "type": "TXT", "changetype": "REPLACE", "records": [ {"content": "\"asdf\"", "disabled": false, "name": "test.example.org.", "ttl": 86400, "type": "TXT" } ] } ] }' -H 'X-API-Key: changeme' http://127.0.0.1:8081/api/v1/servers/localhost/zones/example.org.
```

Unfortunately debug symbols are unavailable right now, bt all looks like this:

```
(gdb) run
Starting program: /usr/bin/pdnsutil check-all-zones
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
__memcmp_sse4_1 () at ../sysdeps/x86_64/multiarch/memcmp-sse4.S:865
865	../sysdeps/x86_64/multiarch/memcmp-sse4.S: No such file or directory.
(gdb) bt full
#0  __memcmp_sse4_1 () at ../sysdeps/x86_64/multiarch/memcmp-sse4.S:865
No locals.
#1  0x00007ffff6cbaeba in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#2  0x00005555555b6aff in main ()
No symbol table info available.
```

**Comment by zeha** [comment]
Broken since d6ddb28a
