### ISSUE TITLE
OpenBSD + -O2 + LuaWrapper + luajit = crashes

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#4909]
- Program: dnsdist
 - Issue type: Bug report

### Short description
When built against luajit with -O2 set, dnsdist crashes on the first luawrapper exception (like when you make a typo in a command).

### Environment
 - Operating system: OpenBSD 5.9/6.0/current from 9 Jan 2017
 - Software version: dnsdist 1.1.0
 - Software source: tar.gz

### Steps to reproduce
1. build with 'CXX=eg++' 'CPP=ecpp' 'LIBEDIT_LIBS=-ledit -lcurses' 'LIBEDIT_CFLAGS= ' '--with-luajit' 'CFLAGS=-O2 -ggdb' 'CXXFLAGS=-O2 -ggdb'
2. start `./dnsdist`
3. type an invalid command (like `showStats()`)

### Expected behaviour
```
> showStats()
[string "return showStats()"]:1: attempt to call global 'showStats' (a nil value)
>
```

### Actual behaviour
```
> showStats()
Abort trap (core dumped)
#
```

### Other information
-O0 and -O1 are fine; Lua (non-Luajit) is fine. -O3 + LuaJit also crashes.

Using egdb, after the crash:
```
> showStats()
[New thread 490826]
[New thread 621683]
[New thread 536240]
[New thread 482330]
[New thread 176933]
[New thread 522579]
[New thread 518328]
[New thread 143884]

Thread 1 received signal SIGABRT, Aborted.
0x00000de705959f2a in thrkill () at <stdin>:2
2       <stdin>: No such file or directory.
(gdb) bt
#0  0x00000de705959f2a in thrkill () at <stdin>:2
#1  0x00000de7059a1399 in *_libc_abort () at /usr/src/lib/libc/stdlib/abort.c:52
#2  0x00000de6ed82f905 in _Unwind_Resume (exc=0xde7206c0660)
    at /usr/src/gnu/usr.bin/cc/libgcc/../../../gcc/gcc/unwind.inc:238
#3  0x00000de462238675 in boost::optional<boost::variant<std::string, std::shared_ptr<DownstreamState>, std::unordered_map<std::string, double, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, double> > >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > LuaContext::executeCode<boost::optional<boost::variant<std::string, std::shared_ptr<DownstreamState>, std::unordered_map<std::string, double, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, double> > >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > >(char const*) ()
#4  0x00000de462230903 in LuaContext::executeCode<boost::optional<boost::variant<std::basic_string<char>, std::shared_ptr<DownstreamState>, std::unordered_map<std::basic_string<char>, double> > > > (code=...,
    this=<optimized out>) at ext/luawrapper/include/LuaContext.hpp:255
#5  doConsole () at dnsdist-console.cc:188
#6  0x00000de462221999 in main ()
```

Using egdb and `catch throw`:
```
> showStats()
[New thread 419332]
[New thread 201867]
[New thread 281615]
[New thread 155741]
[New thread 375791]
[New thread 381670]
[New thread 259547]
[New thread 329336]

Thread 1 hit Catchpoint 1 (exception thrown), __cxxabiv1::__cxa_throw (obj=0x1ac45ff2f480,
    tinfo=0x1ac180acb200 <typeinfo for LuaContext::ExecutionErrorException>,
    dest=0x1ac18060e940 <LuaContext::ExecutionErrorException::~ExecutionErrorException()>)
    at /usr/obj/ports/gcc-4.9.4/gcc-4.9.4/libstdc++-v3/libsupc++/eh_throw.cc:62
62      /usr/obj/ports/gcc-4.9.4/gcc-4.9.4/libstdc++-v3/libsupc++/eh_throw.cc: No such file or directory.
(gdb) bt
#0  __cxxabiv1::__cxa_throw (obj=0x1ac45ff2f480,
    tinfo=0x1ac180acb200 <typeinfo for LuaContext::ExecutionErrorException>,
    dest=0x1ac18060e940 <LuaContext::ExecutionErrorException::~ExecutionErrorException()>)
    at /usr/obj/ports/gcc-4.9.4/gcc-4.9.4/libstdc++-v3/libsupc++/eh_throw.cc:62
#1  0x00001ac1806389b0 in boost::optional<boost::variant<std::string, std::shared_ptr<DownstreamState>, std::unordered_map<std::string, double, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, double> > >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > LuaContext::executeCode<boost::optional<boost::variant<std::string, std::shared_ptr<DownstreamState>, std::unordered_map<std::string, double, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, double> > >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > >(char const*) ()
#2  0x00001ac180630903 in LuaContext::executeCode<boost::optional<boost::variant<std::basic_string<char>, std::shared_ptr<DownstreamState>, std::unordered_map<std::basic_string<char>, double> > > > (code=...,
    this=<optimized out>) at ext/luawrapper/include/LuaContext.hpp:255
#3  doConsole () at dnsdist-console.cc:188
#4  0x00001ac180621999 in main ()
```

**Comment by omoerbeek** [comment]
I the current port (OpenBSD 6.4) -O3 is patched out, and dnsdist is built with the default optimization level (-O2) using the now default base compiler clang. . With that I'm unable to reproduce the abort. 

```
> showStats()
[string "return showStats()"]:1: attempt to call a nil value (global 'showStats')
>
```
