### ISSUE TITLE
Swagger generate throws error on authoritative-api-swagger.yaml

### ISSUE THREAD

**Issue by muffinista** [PowerDNS/pdns#6431]
- Program: Authoritative
 - Issue type: Bug report

### Short description

I am attempting to generate a client via `swagger-codegen-cli.jar` using `authoritative-api-swagger.yaml`, but I get an error. 

### Environment

 - Operating system: OSX
 - Software version: 10.13.4
 - Software source: PowerDNS repository

### Steps to reproduce

1. Clone the repository
2. Clone [https://github.com/swagger-api/swagger-codegen](https://github.com/swagger-api/swagger-codegen)
3. Run ```java -jar /path/to/swagger-codegen-cli.jar generate -l go -i docs/http-api/swagger/authoritative-api-swagger.yaml -o /tmp/foo```

### Expected behaviour
No errors and a working client library

### Actual behaviour

```
[main] ERROR io.swagger.codegen.DefaultCodegen - unexpected missing property for name response
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: Tag {
	name: stats
	description: null
	externalDocs: null
	extensions:{}}
  Operation: getStats
  Resource: get /servers/{server_id}/statistics
  Definitions: {Server=io.swagger.models.ModelImpl@4c0a8a90, Servers=io.swagger.models.ArrayModel@2b7fb64f, Zone=io.swagger.models.ModelImpl@5f984275, Zones=io.swagger.models.ArrayModel@2d3bafef, RRSet=io.swagger.models.ModelImpl@c5c56740, Record=io.swagger.models.ModelImpl@7b4b318b, Comment=io.swagger.models.ModelImpl@fdca315b, ConfigSetting=io.swagger.models.ModelImpl@60b319d3, BaseStatisticItem=io.swagger.models.ModelImpl@15fcf1ff, StatisticItem=io.swagger.models.ComposedModel@e4895601, MapStatisticItem=io.swagger.models.ComposedModel@fe371481, RingStatisticItem=io.swagger.models.ComposedModel@15ee93e1, SearchResultZone=io.swagger.models.ModelImpl@b148af6e, SearchResultRecord=io.swagger.models.ModelImpl@a8f379bb, SearchResultComment=io.swagger.models.ModelImpl@2f141712, SearchResult=io.swagger.models.ModelImpl@5a10fa7, SearchResults=io.swagger.models.ArrayModel@cbdf89cf, Metadata=io.swagger.models.ModelImpl@b309bd43, Cryptokey=io.swagger.models.ModelImpl@aafd65a8, MapStatisticItem_value=io.swagger.models.ModelImpl@6ea24a5}
  Exception: null
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:932)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:808)
	at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:431)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:746)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.NullPointerException
	at io.swagger.codegen.DefaultCodegen.fromResponse(DefaultCodegen.java:2340)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:2127)
	at io.swagger.codegen.languages.RubyClientCodegen.fromOperation(RubyClientCodegen.java:267)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:881)
	... 5 more
```

Here's [a gist](https://gist.github.com/muffinista/056c4c0c38f1a27a69534adcbf8e7e47) of the entire output. I'm trying to generate a client in ruby, but I've tried a few other output formats and they return the same error.

### Other information
The error seems to be in the `/servers/{server_id}/statistics` definition, and commenting out the response items and replacing them with `type: string` resolves the error, although presumably isn't helpful for anyone who needs the actual data.

This is originally mentioned in #6421 

Thanks!

**Comment by ffledgling** [comment]
Wanted to confirm I see similar errors when generating a golang client. Requires further debugging to figure if this is invalid swagger spec or a swagger-codegen bug.

```
[main] ERROR io.swagger.codegen.DefaultCodegen - String to be sanitized is null. Default to ERROR_UNKNOWN
[main] ERROR io.swagger.codegen.DefaultCodegen - unexpected missing property for name Response
[main] WARN io.swagger.codegen.DefaultCodegen - skipping invalid array property {
  "baseName" : "response",
  "getter" : "getResponse",
  "setter" : "setResponse",
  "datatype" : "[]ErrorUnknown",
  "datatypeWithEnum" : "[]ErrorUnknown",
  "name" : "Response",
  "defaultValue" : "null",
  "defaultValueWithParam" : " = data.response;",
  "baseType" : "array",
  "containerType" : "array",
  "jsonSchema" : "{\n  \"type\" : \"array\"\n}",
  "exclusiveMinimum" : false,
  "exclusiveMaximum" : false,
  "hasMore" : false,
  "required" : false,
  "secondaryParam" : false,
  "hasMoreNonReadOnly" : false,
  "isPrimitiveType" : false,
  "isContainer" : true,
  "isNotContainer" : false,
  "isString" : false,
  "isNumeric" : false,
  "isInteger" : false,
  "isLong" : false,
  "isNumber" : false,
  "isFloat" : false,
  "isDouble" : false,
  "isByteArray" : false,
  "isBinary" : false,
  "isFile" : false,
  "isBoolean" : false,
  "isDate" : false,
  "isDateTime" : false,
  "isUuid" : false,
  "isListContainer" : true,
  "isMapContainer" : false,
  "isEnum" : false,
  "isReadOnly" : false,
  "vendorExtensions" : { },
  "hasValidation" : false,
  "isInherited" : false,
  "nameInCamelCase" : "Response",
  "isXmlAttribute" : false,
  "isXmlWrapped" : false
}
[main] ERROR io.swagger.codegen.DefaultCodegen - unexpected missing property for name response
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: Tag {
	name: stats
	description: null
	externalDocs: null
	extensions:{}}
  Operation: getStats
  Resource: get /servers/{server_id}/statistics
  Definitions: {Server=io.swagger.models.ModelImpl@4c0a8a90, Servers=io.swagger.models.ArrayModel@a6ebf21, Zone=io.swagger.models.ModelImpl@592fcff5, Zones=io.swagger.models.ArrayModel@c2ab8c1, RRSet=io.swagger.models.ModelImpl@adeb0562, Record=io.swagger.models.ModelImpl@7b4b318b, Comment=io.swagger.models.ModelImpl@fdca315b, ConfigSetting=io.swagger.models.ModelImpl@60b319d3, BaseStatisticItem=io.swagger.models.ModelImpl@15fcf1ff, StatisticItem=io.swagger.models.ComposedModel@e99bd941, MapStatisticItem=io.swagger.models.ComposedModel@c3647981, RingStatisticItem=io.swagger.models.ComposedModel@1afbf8e1, SearchResultZone=io.swagger.models.ModelImpl@b148af6e, SearchResultRecord=io.swagger.models.ModelImpl@a8f379bb, SearchResultComment=io.swagger.models.ModelImpl@2f141712, SearchResult=io.swagger.models.ModelImpl@5a10fa7, SearchResults=io.swagger.models.ArrayModel@aace92a1, Metadata=io.swagger.models.ModelImpl@b309bd43, Cryptokey=io.swagger.models.ModelImpl@aafd65a8, MapStatisticItem_value=io.swagger.models.ModelImpl@6ea24a5}
  Exception: null
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:932)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:808)
	at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:431)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:746)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.NullPointerException
	at io.swagger.codegen.DefaultCodegen.fromResponse(DefaultCodegen.java:2338)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:2125)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:881)
	... 5 more
```
Source: https://travis-ci.org/ffledgling/pdns-go-tooling/builds/367032177

**Comment by friek** [comment]
This is probably due to the fact that on [this line](https://github.com/PowerDNS/pdns/blob/016a165ef72b88c9b23374b701063ac6deb2d25e/docs/http-api/swagger/authoritative-api-swagger.yaml#L416) in the swagger spec items is an array instead of an object. 
When I load the spec in the (Swagger Editor)[https://editor.swagger.io] it also complains about it:
```
Structural error at paths./servers/{server_id}/statistics.get.responses.200.schema.items
should be object
Jump to line 416
Semantic error at paths./servers/{server_id}/statistics.get.responses.200.schema.items
`items` must be an object
Jump to line 416
```

The getStats call returns items in of 3 different types. When there's no discriminator in such a type, it's hardly possible for a generated client to determine which object type is returned, and a such can't deserialize into the right class. 

To solve this, the StatisticItem, MapStatisticItem and RingStatisticItem should get a discriminator and the config stanza on line 416 should be replaced with an anyOf.
