### ISSUE TITLE
PostgreSQL backend: segfault when reconnecting

### ISSUE THREAD

**Issue by cbay** [PowerDNS/pdns#6463]
On PowerDNS authoritative 4.1.1 (Debian, compiled by myself), I reliably get this crash when the PostgreSQL connection is reset:

```
GSQLBackend::lookup (this=this@entry=0x7fffd00009a0, qtype=..., qname=..., pkt_p=pkt_p@entry=0x0, domain_id=domain_id@entry=-1) at backends/gsql/gsqlbackend.cc:1035
1035              bind("qtype", qtype.getName())->
(gdb) bt
#0  GSQLBackend::lookup (this=this@entry=0x7fffd00009a0, qtype=..., qname=..., pkt_p=pkt_p@entry=0x0, domain_id=domain_id@entry=-1) at backends/gsql/gsqlbackend.cc:1035
#1  0x0000555555672cd4 in DNSBackend::getSOA (this=0x7fffd00009a0, domain=..., sd=...) at dnsbackend.cc:219
#2  0x00005555557f5e8a in UeberBackend::getAuth (this=0x7fffd00008d8, this@entry=0x7fffd001b1c0, target=..., qtype=..., sd=sd@entry=0x7fffeaffccc0, cachedOk=cachedOk@entry=true) at ueberbackend.cc:311
#3  0x0000555555785d48 in PacketHandler::doQuestion (this=0x7fffeaffcb10, this@entry=0x7fffd00008c0, p=p@entry=0x7fffe4001660) at packethandler.cc:1215
#4  0x0000555555787ce9 in PacketHandler::question (this=this@entry=0x7fffd00008c0, p=0x7fffe4001660) at packethandler.cc:909
#5  0x0000555555658e3e in MultiThreadDistributor<DNSPacket, DNSPacket, PacketHandler>::makeThread (p=0x7fffe4000900) at distributor.hh:207
#6  0x00007ffff7684064 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007ffff5e6c62d in clone () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) p *d_query_stmt
$1 = std::unique_ptr<SSqlStatement> containing 0x0
```

This can easily be reproduced with `socat`. In my case, I have a local PostgreSQL server listening on port 5432, but I start socat with `socat tcp-listen:8432,reuseaddr,fork tcp:localhost:5432` and tell PowerDNS to connect to port 8432.

Start PowerDNS, stop socat and send a query to PowerDNS, it will crash. My real use case is that I use haproxy to proxy to 2 replicated PostgreSQL servers (for reliability), and PowerDNS would crash when I did a failover.

I looked at the code and it looks like prepared statements are not reinitialized after the reconnect, hence the crash (`d_query_stmt` is invalid).

The following crude patch fixes the issue for me:

```patch
--- pdns-4.1.1/modules/gpgsqlbackend/gpgsqlbackend.cc   2018-02-16 10:52:29.000000000 +0100
+++ pdns-4.1.1~/modules/gpgsqlbackend/gpgsqlbackend.cc  2018-04-10 13:04:46.272035356 +0200
@@ -56,11 +56,13 @@
 
 void gPgSQLBackend::reconnect()
 {
-  freeStatements();
+  setDB(new SPgSQL(getArg("dbname"),
+          getArg("host"),
+          getArg("port"),
+          getArg("user"),
+          getArg("password"),
+          getArg("extra-connection-parameters")));
 
-  if (d_db) {
-    d_db->reconnect();
-  }
 }
 
 bool gPgSQLBackend::inTransaction()

```

**Comment by rgacogne** [comment]
Looks like it was introduced in #5245, sorry about that. I should be able to provide a fix later today.
