### ISSUE TITLE
dnsdist and TLS 1.3

### ISSUE THREAD

**Issue by SasanKSMC** [PowerDNS/pdns#7716]
dnsdist currently supports TLS up to 1.2 only. 
I was wondering if it is possible to update the openssl function in the dnsdist code to let the TLS 1.3 ciphers to be processed correctly?

**Comment by pieterlexis** [comment]
When I link against openssl 1.1.1b TLS 1.3 works:

```
$ openssl s_client -tls1_3 -connect 127.0.0.1:8853
CONNECTED(00000003)
[ ... ]
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 19 (self signed certificate in certificate chain)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: B0F42A3CEDE8EBDC12FF6A2BBE11FD4DECB03F601DE2B55B1EA86AC4284E1C77
    Session-ID-ctx: 
```

**Comment by SasanKSMC** [comment]
if you set the  "TLS_AES_256_GCM_SHA384" in ciphers in "addTLSLocal" function within config file then you will see that dnsdist will fail to load.

**Comment by pieterlexis** [comment]
> if you set the "TLS_AES_256_GCM_SHA384" in ciphers in "addTLSLocal" function within config file then you will see that dnsdist will fail to load.

The template presented when you open an issue tells you (among other things) to fill this in. If you would have done so, we'd have more information. Please provide with the following information:

> - Operating system: 
> - Software version: 
> - Software source: 
> Steps to reproduce

On another note, setting this in the dnsdist config makes it crash on connection:

```lua
addTLSLocal("127.0.0.1:8853", "server.chain", "server.key", {ciphers='TLS_AES_256_GCM_SHA384'})
```

```
Error setting up TLS cipher preferences to TLS_AES_256_GCM_SHA384: (The request is invalid.), skipping.
[ .... ]
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error setting ciphers to TLS connection
```

```
#0  0x00007ffff6eebd7f in raise () from /usr/lib/libc.so.6
#1  0x00007ffff6ed6672 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff72a058e in __gnu_cxx::__verbose_terminate_handler () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff72a6dfa in __cxxabiv1::__terminate (handler=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007ffff72a6e57 in std::terminate () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007ffff72a70fe in __cxxabiv1::__cxa_rethrow () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:133
#6  0x00005555560717a1 in handleIncomingTCPQuery (pipefd=11, param=...) at dnsdist-tcp.cc:1169
#7  0x000055555607c543 in boost::detail::function::void_function_invoker2<void (*)(int, boost::any&), void, int, boost::any&>::invoke (function_ptr=..., a0=11, a1=...) at /usr/include/boost/function/function_template.hpp:117
#8  0x00005555560d5df8 in boost::function2<void, int, boost::any&>::operator() (this=0x7fffe40040a0, a0=11, a1=...) at /usr/include/boost/function/function_template.hpp:763
#9  0x00005555560fbf71 in EpollFDMultiplexer::run (this=0x7fffe4000b20, now=0x7fffee7fb4b0, timeout=500) at epollmplexer.cc:159
#10 0x0000555556071962 in tcpClientThread (pipefd=11) at dnsdist-tcp.cc:1189
#11 0x00005555560778df in std::__invoke_impl<void, void (*)(int), int> (__f=@0x7fffe8000b30: 0x5555560717d8 <tcpClientThread(int)>, __args#0=@0x7fffe8000b28: 11) at /usr/include/c++/8.2.1/bits/invoke.h:60
#12 0x0000555556075922 in std::__invoke<void (*)(int), int> (__fn=@0x7fffe8000b30: 0x5555560717d8 <tcpClientThread(int)>, __args#0=@0x7fffe8000b28: 11) at /usr/include/c++/8.2.1/bits/invoke.h:95
#13 0x000055555607fad3 in std::thread::_Invoker<std::tuple<void (*)(int), int> >::_M_invoke<0ul, 1ul> (this=0x7fffe8000b28) at /usr/include/c++/8.2.1/thread:244
#14 0x000055555607fa24 in std::thread::_Invoker<std::tuple<void (*)(int), int> >::operator() (this=0x7fffe8000b28) at /usr/include/c++/8.2.1/thread:253
#15 0x000055555607f858 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(int), int> > >::_M_run (this=0x7fffe8000b20) at /usr/include/c++/8.2.1/thread:196
#16 0x00007ffff72d3063 in std::execute_native_thread_routine (__p=0x7fffe8000b20) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#17 0x00007ffff73ada9d in start_thread () from /usr/lib/libpthread.so.0
#18 0x00007ffff6fafb23 in clone () from /usr/lib/libc.so.6
```

**Comment by rgacogne** [comment]
Fixed in https://github.com/PowerDNS/pdns/pull/7726.
