### ISSUE TITLE
fully switch to Python3

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#7740]
Right now, our testing scripts are a mix of python 2 and 3, with some working on both. This ticket collects the status of that, and any related thoughts.

I'll start:

This makes the dnsdist tests run and pass under py3 for me:
```diff
diff --git a/regression-tests.dnsdist/requirements.txt b/regression-tests.dnsdist/requirements.txt
index 7fbe25b04..735679ff9 100644
--- a/regression-tests.dnsdist/requirements.txt
+++ b/regression-tests.dnsdist/requirements.txt
@@ -2,7 +2,6 @@ dnspython>=1.11,<1.16.0
 nose>=1.3.7
 libnacl>=1.4.3
 requests>=2.1.0
-protobuf>=2.5,<3.0; sys_platform != 'darwin' and sys_platform != 'openbsd6'
-protobuf>=3.0; sys_platform == 'darwin' or sys_platform == 'openbsd6'
+protobuf>=3.0
 pysnmp>=4.3.4
 future>=0.17.1
diff --git a/regression-tests.dnsdist/test_Protobuf.py b/regression-tests.dnsdist/test_Protobuf.py
index f8345d209..7f720830d 100644
--- a/regression-tests.dnsdist/test_Protobuf.py
+++ b/regression-tests.dnsdist/test_Protobuf.py
@@ -417,7 +417,7 @@ class TestProtobufIPCipher(DNSDistProtobufTest):
                                     3600,
                                     dns.rdataclass.IN,
                                     dns.rdatatype.CNAME,
-                                    target)
+                                    target.decode('ascii'))
         response.answer.append(rrset)

         rrset = dns.rrset.from_text(target,
```

**Comment by rgacogne** [comment]
Doesn't work too well for me on Arch, alternative proposal:
```diff
diff --git a/regression-tests.dnsdist/test_Protobuf.py b/regression-tests.dnsdist/test_Protobuf.py
index f8345d209..103cd2234 100644
--- a/regression-tests.dnsdist/test_Protobuf.py
+++ b/regression-tests.dnsdist/test_Protobuf.py
@@ -409,7 +409,7 @@ class TestProtobufIPCipher(DNSDistProtobufTest):
         """
         name = 'query.protobuf-ipcipher.tests.powerdns.com.'
 
-        target = b'target.protobuf-ipcipher.tests.powerdns.com.'
+        target = 'target.protobuf-ipcipher.tests.powerdns.com.'
         query = dns.message.make_query(name, 'A', 'IN')
         response = dns.message.make_response(query)
 
@@ -450,7 +450,7 @@ class TestProtobufIPCipher(DNSDistProtobufTest):
         self.assertEquals(len(msg.response.rrs), 2)
         rr = msg.response.rrs[0]
         self.checkProtobufResponseRecord(rr, dns.rdataclass.IN, dns.rdatatype.CNAME, name, 3600)
-        self.assertEquals(rr.rdata, target)
+        self.assertEquals(rr.rdata.decode('ascii'), target)
         rr = msg.response.rrs[1]
         self.checkProtobufResponseRecord(rr, dns.rdataclass.IN, dns.rdatatype.A, target, 3600)
         self.assertEquals(socket.inet_ntop(socket.AF_INET, rr.rdata), '127.0.0.1')
@@ -476,7 +476,7 @@ class TestProtobufIPCipher(DNSDistProtobufTest):
         self.assertEquals(len(msg.response.rrs), 2)
         rr = msg.response.rrs[0]
         self.checkProtobufResponseRecord(rr, dns.rdataclass.IN, dns.rdatatype.CNAME, name, 3600)
-        self.assertEquals(rr.rdata, target)
+        self.assertEquals(rr.rdata.decode('ascii'), target)
         rr = msg.response.rrs[1]
         self.checkProtobufResponseRecord(rr, dns.rdataclass.IN, dns.rdatatype.A, target, 3600)
         self.assertEquals(socket.inet_ntop(socket.AF_INET, rr.rdata), '127.0.0.1')
```

**Comment by Habbie** [comment]
With protobuf at 2.x or 3.x?

**Comment by Habbie** [comment]
With protobuf at 3.x, your version does not work for me. I'll grab two systems in parallel sometime soon to work out the common ground.

**Comment by rgacogne** [comment]
hmm, `pip show protobuf` reports `Version: 3.7.0` but I have always been confused about protobuf 2.x vs 3.x so I'm probably missing the point :-/

**Comment by zeha** [comment]
for regression-tests.auth-py I tried https://gist.github.com/zeha/0d5a030d9e69a642c7fde9d3ba803519 , but tbf, on mac the tests already fail (somewhat randomly) without switching python versions for me:

```
======================================================================
FAIL: Basic ifurlup() test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ch/Source/Deduktiva/pdns/regression-tests.auth-py/test_LuaRecords.py", line 307, in testIfurlup
    self.assertAnyRRsetInAnswer(res, reachable_rrs)
  File "/Users/ch/Source/Deduktiva/pdns/regression-tests.auth-py/authtests.py", line 443, in assertAnyRRsetInAnswer
    "\n".join(([rrset.to_text() for rrset in rrsets])),
AssertionError: RRset not found in answer
Answer: usa.example.org. 3600 IN A 192.168.42.102
Expected: usa.example.org. 0 IN A 127.0.0.103
```

**Comment by Habbie** [comment]
> Doesn't work too well for me on Arch, alternative proposal:

On Debian Buster my version also does not work, and yours does.

**Comment by Habbie** [comment]
#7811 updates dnsdist testing to py3.

**Comment by omoerbeek** [comment]
This is done, right?

**Comment by Habbie** [comment]
There are a few mentions of python2 still sprinkled around the codebase, but this migration is sufficiently done.
